export const enum actionTypes {
  GET_ALL_EXHIBITIONS_REQUEST,
  GET_ALL_EXHIBITIONS_SUCCESS,
  GET_ALL_EXHIBITIONS_ERROR,

  GET_EXHIBITIONS_REQUEST,
  GET_EXHIBITIONS_SUCCESS,
  GET_EXHIBITIONS_ERROR,
}
export const GET_ALL_EXHIBITIONS_REQUEST = "GET_ALL_EXHIBITIONS_REQUEST";
export const GET_ALL_EXHIBITIONS_SUCCESS = "GET_ALL_EXHIBITIONS_SUCCESS";
export const GET_ALL_EXHIBITIONS_ERROR = "GET_ALL_EXHIBITIONS_ERROR";

export const GET_EXHIBITIONS_REQUEST = "GET_EXHIBITIONS_REQUEST";
export const GET_EXHIBITIONS_SUCCESS = "GET_EXHIBITIONS_SUCCESS";
export const GET_EXHIBITIONS_ERROR = "GET_EXHIBITIONS_ERROR";
